/*
 * Created on June 6, 2012, 1:44 PM
 */
package oui.mapper;
import oui.gui.OuiGISPanel;

/**
 *
 * @author  markstro
 */
public class MapFrame extends javax.swing.JFrame {
    OuiGISPanel ouiGisPanel = null;

    public MapFrame() {
        initComponents();
        ouiGisPanel = new OuiGISPanel(mapPanel, featureLabel, null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        tracking_panel = new javax.swing.JPanel();
        featureLabel = new javax.swing.JLabel();

        setTitle("oui");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        mapPanel.setPreferredSize(new java.awt.Dimension(800, 800));
        mapPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mapPanel, java.awt.BorderLayout.CENTER);

        tracking_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Tracking"));
        tracking_panel.setLayout(new java.awt.BorderLayout());

        featureLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        featureLabel.setText(" ");
        featureLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        tracking_panel.add(featureLabel, java.awt.BorderLayout.WEST);

        getContentPane().add(tracking_panel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
{//GEN-HEADEREND:event_exitForm
	quit();
}//GEN-LAST:event_exitForm

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel featureLabel;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JPanel tracking_panel;
    // End of variables declaration//GEN-END:variables

    private void quit() {
        System.exit(0);
    }

    public OuiGISPanel getGisPanel() {
        return ouiGisPanel;
    }
}
