/*
 * MmsInputDataFromDssGui.java
 *
 * Created on June 22, 2004, 3:43 PM
 */

package oui.mms.mmi;

import gov.usgs.cawsc.gui.MenuBarProvider;
import gov.usgs.cawsc.gui.WindowFactory;
import java.util.Calendar;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import oui.mms.datatypes.OuiCalendar;

/**
 *
 * @author  markstro
 */
public class MmsRunSimpleGui extends JPanel implements MenuBarProvider {
    private MmsSingleModelRunner srm;

    /** Creates new form MmsInputDataFromDssGui */
    public MmsRunSimpleGui(String mmsDataFileName, OuiCalendar data_file_start, OuiCalendar data_file_end, MmsSingleModelRunner srm) {
        this(mmsDataFileName, data_file_start, data_file_end, null, srm);
    }

    public MmsRunSimpleGui(String mmsDataFileName, OuiCalendar data_file_start, OuiCalendar data_file_end, OuiCalendar state_date, MmsSingleModelRunner srm) {
        this.srm = srm;
        initComponents();

        mmsDataFileLable.setText("MMS Input Data File: " + mmsDataFileName);
        dateLabel.setText("(has data from " + data_file_start.getSQLDate() + " to " + data_file_end.getSQLDate() + ")");

        /*
         *  Set the default start date to start of the data file
         */
        queryStart = (OuiCalendar)(data_file_start.clone());

        /*
         * Set the default end date to end of the data file
         */
        queryEnd = (OuiCalendar)(data_file_end.clone());

        /*
         * Set the end limit of the forecast to one year after the end of the data file
         */
        startSpinner.setModel(new SpinnerDateModel(queryStart.getTime(), data_file_start.getTime(), data_file_end.getTime(), Calendar.DAY_OF_MONTH));
        startSpinner.setEditor(new JSpinner.DateEditor(startSpinner, "yyyy-MM-dd"));

        endSpinner.setModel(new SpinnerDateModel(queryEnd.getTime(), data_file_start.getTime(), data_file_end.getTime(), Calendar.DAY_OF_MONTH));
        endSpinner.setEditor(new JSpinner.DateEditor(endSpinner, "yyyy-MM-dd"));

        this.setSize(this.getPreferredSize());
    }

    public JMenuBar getMenuBar() {
        return jMenuBar1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit_menu_item = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        mmsDataFileLable = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        runButton = new javax.swing.JButton();
        startSpinner = new javax.swing.JSpinner();
        endSpinner = new javax.swing.JSpinner();

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setText("File");

        exit_menu_item.setText("Exit");
        exit_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonPushed(evt);
            }
        });
        jMenu1.add(exit_menu_item);

        jMenuBar1.add(jMenu1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mmsDataFileLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmsDataFileLable.setText("MMS Input Data File:");

        dateLabel.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText("(has data from ....)");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Run Start Date:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Run End Date:");

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonPushed(evt);
            }
        });

        startSpinner.setName("startSpinner"); // NOI18N
        startSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                startSpinnerChange(evt);
            }
        });

        endSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                endSpinnerChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mmsDataFileLable)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(runButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(startSpinner)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mmsDataFileLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jMenuBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonPushed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonPushed
        if (srm != null) {
            srm.runModel (queryStart, queryEnd);
        } else {
            System.out.println ("run button pushed");
        }
    }//GEN-LAST:event_runButtonPushed

    private void endSpinnerChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_endSpinnerChange
        SpinnerModel dateModel = endSpinner.getModel();
        if (dateModel instanceof SpinnerDateModel) {
            queryEnd.setTime(((SpinnerDateModel)dateModel).getDate());
        }
    }//GEN-LAST:event_endSpinnerChange

    private void startSpinnerChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_startSpinnerChange
        SpinnerModel dateModel = startSpinner.getModel();
        if (dateModel instanceof SpinnerDateModel) {
            queryStart.setTime(((SpinnerDateModel)dateModel).getDate());
        }
    }//GEN-LAST:event_startSpinnerChange

    private void exitButtonPushed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonPushed
        WindowFactory.instance().closeWindow(this);
    }//GEN-LAST:event_exitButtonPushed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        WindowFactory.instance().closeWindow(this);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MmsRunSimpleGui gui = new MmsRunSimpleGui("mmsDataFileName", null, null, null);
        WindowFactory.displayInFrame(gui, "Run MMS Model");
    }

    /**
     * Getter for property queryEnd.
     * @return Value of property queryEnd.
     */
    public OuiCalendar getQueryEnd() {
        return this.queryEnd;
    }

    /**
     * Setter for property queryEnd.
     * @param queryEnd New value of property queryEnd.
     */
    public void setQueryEnd(OuiCalendar queryEnd) {
        this.queryEnd = queryEnd;
    }

    /**
     * Getter for property queryStart.
     * @return Value of property queryStart.
     */
    public OuiCalendar getQueryStart() {
        return this.queryStart;
    }

    /**
     * Setter for property queryStart.
     * @param queryStart New value of property queryStart.
     */
    public void setQueryStart(OuiCalendar queryStart) {
        this.queryStart = queryStart;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JSpinner endSpinner;
    private javax.swing.JMenuItem exit_menu_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mmsDataFileLable;
    private javax.swing.JButton runButton;
    private javax.swing.JSpinner startSpinner;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property queryEnd.
     */
    private OuiCalendar queryEnd;

    /**
     * Holds value of property queryStart.
     */
    private OuiCalendar queryStart;

}
