/*
 * SpagtiFrame.java
 *
 * Created on October 30, 2006, 9:42 AM
 */

package oui.dogbyte;

/**
 *
 * @author  markstro
 */
public class DogbyteFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form SpagtiFrame
     */
    public DogbyteFrame() {
        initComponents();
    }
//    
//    public SpagtiFrame(SpagiToolPanel stp) {
//        initComponents();
//        setContentPane(stp);
//    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spatial Parameter And Geo-informaTion Interface");
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DogbyteFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property topLevel.
     */
    private boolean topLevel = false;

    /**
     * Getter for property isTopLevel.
     * @return Value of property isTopLevel.
     */
    public boolean isTopLevel() {
        return this.topLevel;
    }

    /**
     * Setter for property isTopLevel.
     * @param isTopLevel New value of property isTopLevel.
     */
    public void setTopLevel(boolean topLevel) {
        this.topLevel = topLevel;
    }
    
}
