/*
 * ReportFrame.java
 *
 * Created on September 7, 2004, 3:43 PM
 */

package oui.util;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author  markstro
 */
public class ReportFrame extends javax.swing.JFrame {
    private boolean topLevel = false;
    
    /** Creates new form ReportFrame */
    public ReportFrame() {
        initComponents();
        writer = new JTextAreaWriter(jTextArea1);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        jTextArea1.setColumns(100);
        jTextArea1.setFont(new java.awt.Font("Courier", 0, 12));
        jTextArea1.setRows(24);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.removeChoosableFileFilter(chooser.getAcceptAllFileFilter());
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setDialogTitle("Save Report File");
        
        chooser.setCurrentDirectory(new File("./"));
        int retval = chooser.showOpenDialog(this);
        
        PrintWriter out = null;
        if(retval == 0) {
            try {
                out = new PrintWriter(new FileWriter(chooser.getSelectedFile()));
                out.println(jTextArea1.getText());
                
            } catch (IOException e) {
                Object[] options = {"OK"};
                int n = JOptionPane.showOptionDialog(this, "Unable to write file.\n" + e.getMessage(), "Problem saving file", JOptionPane.OK_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
            } finally {
                if (out != null) out.close();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        if (topLevel) {
            System.exit(0);
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ReportFrame().setVisible(true);
    }
    
    /**
     * Getter for property writer.
     * @return Value of property writer.
     */
    public JTextAreaWriter getWriter() {
        return this.writer;
    }
    
    /**
     * Setter for property writer.
     * @param writer New value of property writer.
     */
    public void setWriter(JTextAreaWriter writer) {
        this.writer = writer;
    }
    
    /**
     * Getter for property topLevel.
     * @return Value of property topLevel.
     */
    public boolean isTopLevel() {
        return this.topLevel;
    }
    
    /**
     * Setter for property topLevel.
     * @param topLevel New value of property topLevel.
     */
    public void setTopLevel(boolean topLevel) {
        this.topLevel = topLevel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property writer.
     */
    private JTextAreaWriter writer;    
    
}
