/*
 * MmsDataFileChooser.java
 *
 * Created on July 14, 2005, 7:33 AM
 */

package oui.mms.gui;

import gov.usgs.cawsc.gui.GuiUtilities;
import gov.usgs.cawsc.gui.WindowFactory;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import oui.util.OuiHelp;

/**
 *
 * @author  markstro
 */
public class MmsDataFileChooser extends JPanel {
    private DefaultListModel selListModel = null;
    private Mms mms;

    /** Creates new form MmsDataFileChooser */
    public MmsDataFileChooser(Mms mms) {
        this.mms = mms;
        initComponents();

        ArrayList<String> dataFiles = mms.getControlValues("data_file");
        selListModel = new DefaultListModel();
        for (int i = 0; i < dataFiles.size(); i++) {
            selListModel.addElement(dataFiles.get(i));
        }
        dataFileList.setModel(selListModel);

        setSize(getPreferredSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataFileList = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        dataFileOKButton = new javax.swing.JButton();
        dataFileCancelButton = new javax.swing.JButton();
        dataFileAddButton = new javax.swing.JButton();
        dataFileHelpButton = new javax.swing.JButton();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Current Data Files:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Time series data will be read from the folowing files.");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select to remove from list.");
        jPanel1.add(jLabel3, java.awt.BorderLayout.SOUTH);

        dataFileList.setOpaque(false);
        dataFileList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                dataFileListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(dataFileList);

        dataFileOKButton.setText("OK");
        dataFileOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFileOKButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dataFileOKButton);

        dataFileCancelButton.setText("Cancel");
        dataFileCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFileCancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dataFileCancelButton);

        dataFileAddButton.setText("Add");
        dataFileAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFileAddButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dataFileAddButton);

        dataFileHelpButton.setText("Help");
        dataFileHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFileHelpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(dataFileHelpButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dataFileListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_dataFileListValueChanged
        int index = dataFileList.getSelectedIndex();
        if (index != -1) selListModel.remove(index);
    }//GEN-LAST:event_dataFileListValueChanged

    private void dataFileCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFileCancelButtonActionPerformed
        exit();
    }//GEN-LAST:event_dataFileCancelButtonActionPerformed

    private void dataFileOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFileOKButtonActionPerformed
        int count = selListModel.getSize();
        ArrayList<String> dataFiles = new ArrayList<String>(count);
        for (int i = 0; i < count; i++) {
            dataFiles.add(i, (String)(selListModel.getElementAt(i)));
        }
        mms.setControlValues("data_file", dataFiles);
        mms.loadVariableFiles();

        // Save the edits to the control file
        mms.saveControlFile();

        // Update the MMS GUI
        mms.updateDataFileListGui();

        exit();
    }//GEN-LAST:event_dataFileOKButtonActionPerformed

    private void dataFileHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFileHelpButtonActionPerformed
        OuiHelp.OuiHelpFactory().showTopic ("");
    }//GEN-LAST:event_dataFileHelpButtonActionPerformed

    private void dataFileAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFileAddButtonActionPerformed
        String fileName = mms.getSingleControlValue("data_file");
        String dirName = null;
        if (fileName != null) {
            int path_index = fileName.lastIndexOf(File.separatorChar);
            if (path_index != -1) {
                dirName = fileName.substring(0, path_index);
            }
        }

        JFileChooser chooser = new JFileChooser(dirName);
        chooser.setDialogTitle("MMS - Add the MMS Data File");

        int returnVal = chooser.showOpenDialog(GuiUtilities.windowFor(this));
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            String modelName = chooser.getSelectedFile().getAbsolutePath();
            if (!selListModel.contains(modelName)) selListModel.addElement(modelName);
        }
    }//GEN-LAST:event_dataFileAddButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        exit();
    }//GEN-LAST:event_exitForm


    private void exit() {
        WindowFactory.instance().closeWindow(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dataFileAddButton;
    private javax.swing.JButton dataFileCancelButton;
    private javax.swing.JButton dataFileHelpButton;
    private javax.swing.JList dataFileList;
    private javax.swing.JButton dataFileOKButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
