/*
 * MmsSingleRunGui.java
 *
 * Created on July 15, 2005, 8:04 AM
 */

package oui.mms.gui;

import gov.usgs.cawsc.gui.GuiUtilities;
import gov.usgs.cawsc.gui.WindowFactory;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import oui.mms.datatypes.OuiCalendar;
import oui.util.OuiHelp;
import oui.util.concurrent.CommandRunner;

/**
 *
 * @author  markstro
 * Swing layout updated by John Donovan
 */
public class MmsEspRunGui extends javax.swing.JPanel implements TableModel {
    CommandRunner runner = null;
    Mms mms;

    /** Creates new form MmsSingleRunGui */
    public MmsEspRunGui(Mms mms) {
        initComponents();
        this.mms = mms;

        timeTable.setModel(this);
        timeTablePanel.add(timeTable.getTableHeader(), java.awt.BorderLayout.NORTH);

        initTimeStepTextField.setText(mms.getSingleControlValue("initial_deltat"));

//        setCheckBox("runTimeOn_Off0", rt1CheckBox);
//        setCheckBox("runTimeOn_Off1", rt2CheckBox);
//        setCheckBox("runTimeOn_Off2", rt3CheckBox);
//        setCheckBox("runTimeOn_Off3", rt4CheckBox);
//        setCheckBox("db_on_off", dbCheckBox);
        setCheckBox("init_vars_from_file", varInitCheckBox);
//        setCheckBox("save_vars_to_file", varSaveCheckBox);
//        setCheckBox("statsON_OFF", statsCheckBox);
//        setCheckBox("statsON_OFF", statVarCheckBox);
//        setCheckBox("gisOutON_OFF", gisOutCheckBox);

//        dbTextField.setText(Mms.getSingleControlValue("db_file_exten"));
        modelOutTextField.setText(mms.getSingleControlValue("model_output_file"));
        varInitTextBox.setText(mms.getSingleControlValue("var_init_file"));
//        varSaveTextBox.setText(Mms.getSingleControlValue("var_save_file"));
//        statsTextBox.setText(Mms.getSingleControlValue("stats_output_file"));
//        statVarTextBox.setText(Mms.getSingleControlValue("stat_var_file"));
//        gisOutTextField.setText(Mms.getSingleControlValue("gis_output_file"));

        setSize(getPreferredSize());
    }

    private void setCheckBox(String controlString, JCheckBox cb) {
        if (mms.getSingleControlValue(controlString).equals("1")) {
            cb.setSelected(true);
        } else {
            cb.setSelected(false);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphingButtonGroup = new javax.swing.ButtonGroup();
        topPanel = new javax.swing.JPanel();
        timePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        initTimeStepTextField = new javax.swing.JTextField();
        timeTablePanel = new javax.swing.JPanel();
        timeTable = new javax.swing.JTable();
        graphPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        filePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        modelOutCheckBox = new javax.swing.JCheckBox();
        modelOutTextField = new javax.swing.JTextField();
        varInitCheckBox = new javax.swing.JCheckBox();
        varInitTextBox = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        timePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(153, 0, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Time Info");
        jLabel1.setOpaque(true);

        jLabel2.setText("Init Timestep");

        initTimeStepTextField.setColumns(10);
        initTimeStepTextField.setText("24.0");
        initTimeStepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initTimeStepTextFieldActionPerformed(evt);
            }
        });
        initTimeStepTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                initTimeStepTextFieldFocusLost(evt);
            }
        });

        timeTablePanel.setLayout(new java.awt.BorderLayout());

        timeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Second", null, null, null, null, null, null},
                {"Minute", null, null, null, null, null, null},
                {"Hour", null, null, null, null, null, null},
                {"Day", null, null, null, null, null, null},
                {"Month", null, null, null, null, null, null},
                {"Year", null, null, null, null, null, null}
            },
            new String [] {
                "", "Init Start", "Init End", "Model Start", "Model End", "Data Start", "Data End"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        timeTable.setOpaque(false);
        timeTablePanel.add(timeTable, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(initTimeStepTextField)
                .addContainerGap())
            .addComponent(timeTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(initTimeStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        graphPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setBackground(new java.awt.Color(153, 0, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ESP Options");
        jLabel3.setOpaque(true);

        jButton1.setText("Set ESP Variables");

        jButton2.setText("Set ESP Series");

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        filePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setBackground(new java.awt.Color(153, 0, 204));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("File Info");
        jLabel4.setOpaque(true);

        modelOutCheckBox.setSelected(true);
        modelOutCheckBox.setText("Model Output:");
        modelOutCheckBox.setEnabled(false);

        modelOutTextField.setColumns(10);
        modelOutTextField.setText("jTextField1");
        modelOutTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modelOutTextFieldFocusLost(evt);
            }
        });
        modelOutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelOutTextFieldActionPerformed(evt);
            }
        });

        varInitCheckBox.setText("Variable Init:");
        varInitCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varInitCheckBoxActionPerformed(evt);
            }
        });

        varInitTextBox.setColumns(10);
        varInitTextBox.setText("jTextField1");
        varInitTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                varInitTextBoxFocusLost(evt);
            }
        });
        varInitTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varInitTextBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filePanelLayout = new javax.swing.GroupLayout(filePanel);
        filePanel.setLayout(filePanelLayout);
        filePanelLayout.setHorizontalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelOutCheckBox)
                    .addComponent(varInitCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelOutTextField)
                    .addComponent(varInitTextBox))
                .addContainerGap())
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        filePanelLayout.setVerticalGroup(
            filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filePanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelOutCheckBox))
                .addGap(1, 1, 1)
                .addGroup(filePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varInitTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(varInitCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(startButton);

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(stopButton);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(closeButton);

        helpButton.setText("Help");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(helpButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(filePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modelOutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelOutTextFieldActionPerformed
        mms.setControlValues("model_output_file", modelOutTextField.getText());
    }//GEN-LAST:event_modelOutTextFieldActionPerformed

    private void modelOutTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelOutTextFieldFocusLost
        mms.setControlValues("model_output_file", modelOutTextField.getText());
    }//GEN-LAST:event_modelOutTextFieldFocusLost

    private void varInitCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varInitCheckBoxActionPerformed
        setOnOff("init_vars_from_file", varInitCheckBox.isSelected());
    }//GEN-LAST:event_varInitCheckBoxActionPerformed

    private void varInitTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varInitTextBoxActionPerformed
        mms.setControlValues("var_init_file", varInitTextBox.getText());
    }//GEN-LAST:event_varInitTextBoxActionPerformed

    private void varInitTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_varInitTextBoxFocusLost
        mms.setControlValues("var_init_file", varInitTextBox.getText());
    }//GEN-LAST:event_varInitTextBoxFocusLost

    private void setOnOff(String controlString, boolean isSet) {
        if (isSet) {
            mms.setControlValues(controlString, "1");
        } else {
            mms.setControlValues(controlString, "0");
        }
    }

    private void initTimeStepTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_initTimeStepTextFieldFocusLost
        mms.setControlValues("initial_deltat", initTimeStepTextField.getText());
    }//GEN-LAST:event_initTimeStepTextFieldFocusLost

    private void initTimeStepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initTimeStepTextFieldActionPerformed
        mms.setControlValues("initial_deltat", initTimeStepTextField.getText());
    }//GEN-LAST:event_initTimeStepTextFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        mms.saveControlFile();

        String env = " -E" + mms.getControlMap().getDirectory() + File.separatorChar + "mms.env";
        String control = " -C" + mms.getControlMap().getShortFileName();
        String executable = mms.getSingleControlValue("executable_model");
        String arg = executable + " -batch" + env + control;
        System.out.println("MmsSingleRunGui: executing = " + arg);

        try {
            runner = new CommandRunner(arg);
            runner.evaluate();
            JOptionPane.showMessageDialog(GuiUtilities.windowFor(this), "Run Completed", "Run Status", JOptionPane.INFORMATION_MESSAGE);
            runner = null;

        } catch (IOException e) {
            JOptionPane.showMessageDialog(GuiUtilities.windowFor(this), "Run Unsuccessful\n" + e.getMessage(), "Run Status", JOptionPane.ERROR_MESSAGE);
            runner = null;
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        OuiHelp.OuiHelpFactory().showTopic ("");
    }//GEN-LAST:event_helpButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        mms.saveControlFile();
        exit();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopButtonActionPerformed

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        exit();
    }//GEN-LAST:event_exitForm

    private void exit() {
        if (mms.isTopLevel()) System.exit(0);
        else WindowFactory.instance().closeWindow(this);
    }


    /*
     *  Here's the table model interface for the time table
     */
    private String[] colNames = {"", "Init Start", "Init End", "Forecast Start", "Forecast End", "Data Start", "Data End"};
    private String[] rowNames = {"Second", "Minute", "Hour", "Day", "Month", "Year"};

    public void addTableModelListener(javax.swing.event.TableModelListener l) {}

    public int getColumnCount() {return 7;}
    public String getColumnName(int columnIndex) {return colNames[columnIndex];}
    public int getRowCount() {return 6;}
    public void removeTableModelListener(javax.swing.event.TableModelListener l) {}

    public Class getColumnClass(int columnIndex) {
        if (columnIndex == 0)
            return String.class;
        else
            return Integer.class;
    }

    public boolean isCellEditable(int rowIndex, int columnIndex) {
        if (columnIndex == 0) return false;
        return true;
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        if (columnIndex == 0) {
            return rowNames[rowIndex];

        } else if (columnIndex == 3){
            return new Integer(mms.getControlValues("start_time").get(5-rowIndex));

        } else if (columnIndex == 4){
            return new Integer(mms.getControlValues("end_time").get(5-rowIndex));

        } else if (columnIndex == 5){
            OuiCalendar dataStart = mms.getVariableSet().getStart();

            if (rowIndex == 0) {
                return new Integer(dataStart.get(Calendar.SECOND));
            } else if (rowIndex == 1) {
                return new Integer(dataStart.get(Calendar.MINUTE));
            } else if (rowIndex == 2) {
                return new Integer(dataStart.get(Calendar.HOUR));
            } else if (rowIndex == 3) {
                return new Integer(dataStart.get(Calendar.DAY_OF_MONTH));
            } else if (rowIndex == 4) {
                return new Integer(dataStart.get(Calendar.MONTH)+1);
            } else {
                return new Integer(dataStart.get(Calendar.YEAR));
            }
        } else if (columnIndex == 6){
            OuiCalendar dataEnd = mms.getVariableSet().getEnd();

            if (rowIndex == 0) {
                return new Integer(dataEnd.get(Calendar.SECOND));
            } else if (rowIndex == 1) {
                return new Integer(dataEnd.get(Calendar.MINUTE));
            } else if (rowIndex == 2) {
                return new Integer(dataEnd.get(Calendar.HOUR));
            } else if (rowIndex == 3) {
                return new Integer(dataEnd.get(Calendar.DAY_OF_MONTH));
            } else if (rowIndex == 4) {
                return new Integer(dataEnd.get(Calendar.MONTH)+1);
            } else {
                return new Integer(dataEnd.get(Calendar.YEAR));
            }
        } else {
            return new Integer(-999);
        }

    }

    public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
        if (columnIndex == 1){
            mms.setControlValues("start_time", 5-rowIndex, aValue.toString());

        } else if (columnIndex == 2){
            mms.setControlValues("end_time", 5-rowIndex, aValue.toString());

        } else {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel filePanel;
    private javax.swing.JPanel graphPanel;
    private javax.swing.ButtonGroup graphingButtonGroup;
    private javax.swing.JButton helpButton;
    private javax.swing.JTextField initTimeStepTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox modelOutCheckBox;
    private javax.swing.JTextField modelOutTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JPanel timePanel;
    private javax.swing.JTable timeTable;
    private javax.swing.JPanel timeTablePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JCheckBox varInitCheckBox;
    private javax.swing.JTextField varInitTextBox;
    // End of variables declaration//GEN-END:variables

}
